######################
# 	Name		: Grace Brown
#	Last Updated: 16 March 2026
#	Filename	: Makefile
#	Purpose		: compilation instructions for lab 7
######################

all:		Dinosaurs

Dinosaurs:	driver.cpp functions.cpp
			g++ -Wall -o dino driver.cpp functions.cpp

run:		Dinosaurs
			./dino

clean:		Dinosaurs
			rm -f dino