
# 	Name		: Grace Brown
#	Last Edited	: 7 March 2026
#	File name	: Makefile
#	Purpose		: Compilation instructions for Lab6.cpp


all:		Labprog									

Labprog:	Lab6.cpp functions.cpp 						#compile with just "make"
			g++ -Wall -o lab Lab6.cpp functions.cpp

run:		Labprog										#run with "make run"
			./lab

clean:		Labprog										#delete .exe with "make clean"
			rm -f lab